version: '2'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}
  elasticsearch_data_local: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
      - mailhog
      - elasticsearch
    links:
      - postgres
      - mailhog
      - elasticsearch
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_USER
      - USE_DOCKER=yes
    ports:
      - "8000:8000"
    command: /start.sh

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    environment:
      - POSTGRES_USER=ask

  elasticsearch:
    image: elasticsearch:2-alpine
    volumes:
      - elasticsearch_data_local:/usr/share/elasticsearch/data
      - ./compose/local/elasticsearch/config:/usr/share/elasticsearch/config
    environment:
      - discovery.zen.minimum_master_nodes=1
    ports:
      - "9200:9200"

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"

  redis:
    image: redis:3.0
